# 3. Procesamiento y Transformación de Datos con Pandas

## Importación de librerías

En esta etapa se importan las bibliotecas necesarias para realizar el proceso de análisis, transformación y almacenamiento de los datos.

La librería **Pandas** proporciona estructuras y herramientas especializadas para la manipulación de datos tabulares, permitiendo realizar operaciones de limpieza, transformación, agregación y análisis de información de manera eficiente.

Por su parte, la librería **SQLite3** permite establecer conexiones con bases de datos SQLite directamente desde Python, facilitando el almacenamiento y consulta de los datos procesados durante el desarrollo de la actividad.

Estas herramientas constituyen la base del flujo ETL (Extract, Transform, Load) implementado en el presente ejercicio.

### Librerías utilizadas

| Librería | Propósito |
|-----------|-----------|
| pandas | Lectura, transformación y análisis de datos |
| sqlite3 | Conexión y gestión de bases de datos SQLite |

In [26]:
import pandas as pd
import sqlite3

## Carga del conjunto de datos

En esta etapa se realiza la lectura del archivo **ventas_techventas.csv** utilizando la librería Pandas. Durante la carga de la información se especifica la codificación UTF-8 para garantizar la correcta interpretación de caracteres especiales y se convierte automáticamente la columna **fecha** al tipo de dato fecha, facilitando posteriores análisis temporales.

Posteriormente, se utiliza el método **head()** para visualizar los primeros registros del conjunto de datos y verificar que la carga se haya realizado correctamente.

### Objetivo

- Leer el archivo CSV que contiene la información de ventas.
- Convertir la columna de fechas a un formato adecuado para análisis.
- Verificar la estructura inicial del conjunto de datos.
- Identificar las columnas disponibles para el proceso de transformación.

### Operaciones realizadas

1. Lectura del archivo CSV.
2. Configuración de la codificación UTF-8.
3. Conversión automática de la columna fecha.
4. Visualización de los primeros registros mediante `head()`.

In [27]:
df = pd.read_csv(
    "ventas_techventas.csv",
    encoding="utf-8",
    parse_dates=["fecha"]
)

df.head()

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor
0,1001,2024-01-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,2.0,1200.0,0.10,Ana L��
1,1002,2024-01-07,C002,Innovatek,Sur,Mouse Inalambrico,Perifericos,15.0,25.0,0.00,Carlos Ruiz
2,"1003,2024-01-10,C003,DataSolutions,Centro,Moni...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1004,2024-01-12,C001,TechCorp SA,Norte,Teclado Mecanico,Perifericos,10.0,85.0,0.10,Luis Mora
4,1005,2024-01-15,C004,CloudNet,Este,Laptop Pro 15,Electronica,3.0,1200.0,0.15,Carlos Ruiz

## Exploración inicial y análisis de calidad de los datos

Antes de realizar cualquier proceso de transformación o análisis, es fundamental comprender la estructura y calidad del conjunto de datos. Para ello se utilizan los métodos **info()** e **isna().sum()**, los cuales permiten identificar el tipo de dato de cada columna y detectar posibles valores faltantes.

La exploración inicial constituye una etapa esencial dentro del proceso de preparación de datos, ya que facilita la identificación de inconsistencias que podrían afectar los resultados del análisis posterior.

### Objetivo

- Examinar la estructura general del DataFrame.
- Identificar el tipo de dato de cada columna.
- Verificar la cantidad de registros disponibles.
- Detectar valores nulos o faltantes.
- Evaluar la calidad inicial del conjunto de datos.

### Métodos utilizados

| Método | Descripción |
|----------|------------|
| `info()` | Muestra información general del DataFrame, tipos de datos y cantidad de valores no nulos |
| `isna().sum()` | Calcula el número de valores faltantes por columna |

In [28]:
df.info()
df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         60 non-null     str
 1   fecha            49 non-null     datetime64[us]
 2   cliente_id       49 non-null     str
 3   cliente_nombre   49 non-null     str
 4   region           49 non-null     str
 5   producto         48 non-null     str
 6   categoria        49 non-null     str
 7   cantidad         49 non-null     float64
 8   precio_unitario  49 non-null     float64
 9   descuento        49 non-null     float64
 10  vendedor         49 non-null     str
dtypes: datetime64[us](1), float64(3), str(7)
memory usage: 9.0 KB

order_id            0
fecha              11
cliente_id         11
cliente_nombre     11
region             11
producto           12
categoria          11
cantidad           11
precio_unitario    11
descuento          11
vendedor           11
dtype: int64

## Limpieza de datos y eliminación de valores nulos

Una vez identificados los registros con información incompleta, se procede a realizar el proceso de limpieza del conjunto de datos. Para ello se utiliza el método **dropna()**, eliminando aquellos registros que presentan valores nulos en campos considerados críticos para el análisis.

Las columnas seleccionadas corresponden a atributos esenciales del proceso de ventas, tales como identificadores, información del cliente, producto, cantidad, precio y vendedor. Mantener registros completos garantiza la consistencia de los cálculos y mejora la calidad de los resultados obtenidos.

### Objetivo

- Eliminar registros con información incompleta.
- Mejorar la calidad del conjunto de datos.
- Garantizar la consistencia de los análisis posteriores.
- Preparar los datos para las etapas de transformación y agregación.

### Columnas validadas

- order_id
- fecha
- cliente_id
- cliente_nombre
- region
- producto
- categoria
- cantidad
- precio_unitario
- descuento
- vendedor

### Procedimiento realizado

1. Identificación de columnas críticas.
2. Eliminación de registros con valores nulos.
3. Creación de una copia independiente del DataFrame limpio.
4. Comparación entre registros originales y registros finales.

In [29]:
df_limpio = df.dropna(subset=[
    "order_id",
    "fecha",
    "cliente_id",
    "cliente_nombre",
    "region",
    "producto",
    "categoria",
    "cantidad",
    "precio_unitario",
    "descuento",
    "vendedor"
]).copy()

print("Registros originales:", len(df))
print("Registros eliminados:", len(df) - len(df_limpio))
print("Registros finales:", len(df_limpio))

Registros originales: 60
Registros eliminados: 12
Registros finales: 48

## Conversión de tipos de datos y validación numérica

Después de eliminar los registros con valores nulos, se realiza una validación adicional sobre las columnas numéricas del conjunto de datos. Este proceso garantiza que los valores almacenados en las columnas **cantidad**, **precio_unitario** y **descuento** sean interpretados correctamente como datos numéricos.

La función **to_numeric()** permite convertir los valores al tipo de dato adecuado. El parámetro `errors="coerce"` transforma cualquier valor inválido o no numérico en valores nulos (NaN), facilitando su posterior identificación y eliminación.

Una vez realizada la conversión, se eliminan los registros que aún presenten valores faltantes en estas columnas críticas y se verifica nuevamente la estructura del DataFrame.

### Objetivo

- Garantizar la integridad de los datos numéricos.
- Detectar valores inconsistentes o mal formateados.
- Preparar el conjunto de datos para cálculos matemáticos.
- Validar la estructura final del DataFrame limpio.

### Columnas convertidas

| Columna | Tipo esperado |
|----------|--------------|
| cantidad | Numérico |
| precio_unitario | Numérico |
| descuento | Numérico |

### Procedimiento realizado

1. Conversión de columnas al formato numérico.
2. Transformación de valores inválidos en NaN.
3. Eliminación de registros con datos numéricos faltantes.
4. Verificación final mediante `info()`.

In [30]:
df_limpio["cantidad"] = pd.to_numeric(df_limpio["cantidad"], errors="coerce")
df_limpio["precio_unitario"] = pd.to_numeric(df_limpio["precio_unitario"], errors="coerce")
df_limpio["descuento"] = pd.to_numeric(df_limpio["descuento"], errors="coerce")

df_limpio = df_limpio.dropna(subset=[
    "cantidad",
    "precio_unitario",
    "descuento"
]).copy()

df_limpio.info()

<class 'pandas.DataFrame'>
Index: 48 entries, 0 to 58
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         48 non-null     str
 1   fecha            48 non-null     datetime64[us]
 2   cliente_id       48 non-null     str
 3   cliente_nombre   48 non-null     str
 4   region           48 non-null     str
 5   producto         48 non-null     str
 6   categoria        48 non-null     str
 7   cantidad         48 non-null     float64
 8   precio_unitario  48 non-null     float64
 9   descuento        48 non-null     float64
 10  vendedor         48 non-null     str
dtypes: datetime64[us](1), float64(3), str(7)
memory usage: 7.2 KB

## Transformación de datos y creación de métricas de negocio

Una vez completado el proceso de limpieza y validación de los datos, se procede a generar nuevas variables que permitan realizar análisis comerciales más completos.

En esta etapa se calculan indicadores relacionados con los ingresos obtenidos por las ventas y se crea una columna temporal que facilitará la elaboración de reportes mensuales.

### Objetivo

- Calcular el ingreso bruto generado por cada venta.
- Calcular el ingreso neto considerando los descuentos aplicados.
- Crear una variable temporal para análisis por mes.
- Preparar los datos para procesos de agregación y generación de indicadores.

### Variables generadas

| Variable | Descripción |
|-----------|------------|
| ingreso_bruto | Resultado de multiplicar la cantidad vendida por el precio unitario |
| ingreso_neto | Ingreso bruto descontando el porcentaje de descuento aplicado |
| mes | Periodo mensual extraído de la fecha de la venta |

### Fórmulas utilizadas

**Ingreso Bruto**

```text
Ingreso Bruto = Cantidad × Precio Unitario
```

**Ingreso Neto**

```text
Ingreso Neto = Ingreso Bruto × (1 - Descuento)
```

### Procedimiento realizado

1. Cálculo del ingreso bruto por registro.
2. Aplicación de descuentos para obtener el ingreso neto.
3. Extracción del mes a partir de la fecha de venta.
4. Visualización de los primeros registros transformados.

In [31]:
df_limpio["ingreso_bruto"] = (
    df_limpio["cantidad"] * df_limpio["precio_unitario"]
)

df_limpio["ingreso_neto"] = (
    df_limpio["ingreso_bruto"] * (1 - df_limpio["descuento"])
)

df_limpio["mes"] = df_limpio["fecha"].dt.to_period("M").astype(str)

df_limpio.head()

,order_id,fecha,cliente_id,cliente_nombre,region,producto,categoria,cantidad,precio_unitario,descuento,vendedor,ingreso_bruto,ingreso_neto,mes
0,1001,2024-01-05,C001,TechCorp SA,Norte,Laptop Pro 15,Electronica,2.0,1200.0,0.10,Ana L��,2400.0,2160.0,2024-01
1,1002,2024-01-07,C002,Innovatek,Sur,Mouse Inalambrico,Perifericos,15.0,25.0,0.00,Carlos Ruiz,375.0,375.0,2024-01
3,1004,2024-01-12,C001,TechCorp SA,Norte,Teclado Mecanico,Perifericos,10.0,85.0,0.10,Luis Mora,850.0,765.0,2024-01
4,1005,2024-01-15,C004,CloudNet,Este,Laptop Pro 15,Electronica,3.0,1200.0,0.15,Carlos Ruiz,3600.0,3060.0,2024-01
5,1006,2024-01-18,C005,Sistemas Globales,Oeste,SSD 1TB,Almacenamiento,20.0,95.0,0.00,Maria Torres,1900.0,1900.0,2024-01

## Generación del resumen mensual de ventas

Con el propósito de obtener una visión consolidada del comportamiento comercial a lo largo del tiempo, se realiza una agrupación de los datos por mes utilizando la función **groupby()** de Pandas.

Posteriormente se aplican diferentes funciones de agregación para calcular indicadores clave de desempeño, incluyendo el número de pedidos, las unidades vendidas y los ingresos generados durante cada periodo.

Este tipo de análisis permite identificar tendencias temporales, evaluar el rendimiento de las ventas y facilitar la elaboración de reportes gerenciales.

### Objetivo

- Consolidar la información de ventas por mes.
- Calcular indicadores comerciales relevantes.
- Analizar la evolución de las ventas a lo largo del tiempo.
- Facilitar la generación de reportes ejecutivos.

### Indicadores calculados

| Indicador | Descripción |
|------------|------------|
| total_pedidos | Cantidad total de pedidos registrados en el mes |
| unidades_vendidas | Suma de unidades comercializadas |
| ingreso_bruto_total | Total de ingresos antes de descuentos |
| ingreso_neto_total | Total de ingresos después de aplicar descuentos |

### Funciones de agregación utilizadas

| Función | Propósito |
|----------|-----------|
| count() | Contar registros |
| sum() | Sumar valores numéricos |
| reset_index() | Restablecer el índice para generar un DataFrame estructurado |

In [32]:
resumen_mensual = df_limpio.groupby("mes").agg(
    total_pedidos=("order_id", "count"),
    unidades_vendidas=("cantidad", "sum"),
    ingreso_bruto_total=("ingreso_bruto", "sum"),
    ingreso_neto_total=("ingreso_neto", "sum")
).reset_index()

resumen_mensual

,mes,total_pedidos,unidades_vendidas,ingreso_bruto_total,ingreso_neto_total
0,2024-01,8,71.0,12425.0,11446.00
1,2024-02,8,97.0,10720.0,9725.00
2,2024-03,9,98.0,13505.0,12459.00
3,2024-04,9,107.0,16260.0,14659.00
4,2024-05,9,97.0,11015.0,9724.75
5,2024-06,5,73.0,9230.0,8286.75

## Evaluación del cumplimiento de metas por vendedor

Con el objetivo de analizar el desempeño comercial de cada vendedor, se construye una tabla de metas mensuales y posteriormente se compara con los ingresos netos generados durante el periodo analizado.

Para ello, primero se define un conjunto de metas comerciales asociadas a cada vendedor. Posteriormente, se calculan los ingresos netos acumulados mediante una agrupación de los datos y se combinan ambas fuentes de información utilizando la función **merge()**.

Finalmente, se calcula el porcentaje de cumplimiento de la meta asignada a cada vendedor, permitiendo evaluar el grado de logro de los objetivos comerciales establecidos.

### Objetivo

- Definir metas comerciales para cada vendedor.
- Calcular los ingresos netos generados por vendedor.
- Integrar información de ventas y objetivos comerciales.
- Determinar el porcentaje de cumplimiento de metas.

### Procedimiento realizado

1. Creación de la tabla de metas mensuales.
2. Agrupación de ventas por vendedor.
3. Cálculo de ingresos netos acumulados.
4. Integración de datos mediante `merge()`.
5. Cálculo del porcentaje de cumplimiento.

### Fórmula utilizada

**Porcentaje de Cumplimiento**

```text
( Ingreso Neto Total / Meta Mensual ) × 100
```

### Indicadores generados

| Indicador | Descripción |
|------------|------------|
| ingreso_neto_total | Total de ingresos netos obtenidos por el vendedor |
| meta_mensual | Objetivo comercial asignado |
| porcentaje_cumplimiento | Nivel de cumplimiento respecto a la meta |

In [33]:
metas = pd.DataFrame({
    "vendedor": ["Ana López", "Carlos Ruiz", "Luis Mora", "María Torres"],
    "meta_mensual": [8000, 7500, 8000, 7000]
})

ventas_vendedor = df_limpio.groupby("vendedor").agg(
    ingreso_neto_total=("ingreso_neto", "sum")
).reset_index()

cumplimiento = pd.merge(
    ventas_vendedor,
    metas,
    on="vendedor",
    how="left"
)

cumplimiento["porcentaje_cumplimiento"] = (
    cumplimiento["ingreso_neto_total"] / cumplimiento["meta_mensual"]
) * 100

cumplimiento

       vendedor  ingreso_neto_total  meta_mensual  porcentaje_cumplimiento
0       Ana L��             18249.0           NaN                      NaN
1   Carlos Ruiz             19255.5        7500.0                 256.7400
2     Luis Mora             18025.0        8000.0                 225.3125
3  Maria Torres             10771.0           NaN                      NaN

## Carga de los datos procesados en SQLite

Una vez finalizadas las etapas de limpieza, transformación y análisis, se procede a almacenar los resultados en una base de datos SQLite. Este proceso corresponde a la fase **Load** dentro del flujo ETL (Extract, Transform, Load).

El almacenamiento de la información en una base de datos relacional permite conservar los datos procesados de forma estructurada y facilita la ejecución de consultas posteriores utilizando SQL.

Durante esta etapa se crean o actualizan tres tablas principales:

- **ventas:** contiene el conjunto de datos limpio y transformado.
- **resumen_mensual:** almacena los indicadores agregados por periodo mensual.
- **cumplimiento_vendedores:** registra los indicadores de desempeño y cumplimiento de metas por vendedor.

### Objetivo

- Persistir los datos procesados en una base de datos SQLite.
- Organizar la información en tablas especializadas.
- Facilitar consultas posteriores mediante SQL.
- Completar la fase de carga del proceso ETL.

### Tablas almacenadas

| Tabla | Descripción |
|---------|------------|
| ventas | Datos limpios y transformados |
| resumen_mensual | Indicadores agregados por mes |
| cumplimiento_vendedores | Indicadores de desempeño comercial |

### Procedimiento realizado

1. Creación de la conexión a SQLite.
2. Exportación del DataFrame principal.
3. Exportación del resumen mensual.
4. Exportación de indicadores de cumplimiento.
5. Confirmación de cambios mediante `commit()`.

In [34]:
conn = sqlite3.connect("techventas.db")

df_limpio.to_sql(
    "ventas",
    conn,
    if_exists="replace",
    index=False
)

resumen_mensual.to_sql(
    "resumen_mensual",
    conn,
    if_exists="replace",
    index=False
)

cumplimiento.to_sql(
    "cumplimiento_vendedores",
    conn,
    if_exists="replace",
    index=False
)

conn.commit()

## Validación de la carga de datos en SQLite

Después de almacenar la información procesada en la base de datos SQLite, es importante verificar que la carga se haya realizado correctamente. Para ello se ejecuta una consulta SQL que cuenta el número total de registros almacenados en la tabla **ventas**.

Esta validación permite confirmar que los datos fueron exportados exitosamente desde Pandas hacia SQLite y que la tabla se encuentra disponible para futuras consultas y análisis.

### Objetivo

- Verificar la correcta creación de la tabla **ventas**.
- Confirmar que los registros fueron almacenados exitosamente.
- Validar la integridad del proceso de carga.
- Comprobar la conectividad entre Python y SQLite.

### Consulta SQL utilizada

```sql
SELECT COUNT(*) AS total_registros
FROM ventas;
```

In [35]:
pd.read_sql_query(
    "SELECT COUNT(*) AS total_registros FROM ventas",
    conn
)

   total_registros
0               48

## Validación de la tabla resumen_mensual

Con el fin de verificar que el proceso de agregación y almacenamiento se realizó correctamente, se consulta la tabla **resumen_mensual** creada durante la fase de transformación de datos.

Esta tabla contiene indicadores consolidados por mes, permitiendo analizar el comportamiento de las ventas a lo largo del tiempo. La validación de esta información confirma que los cálculos agregados fueron almacenados correctamente en la base de datos SQLite.

### Objetivo

- Verificar la correcta creación de la tabla **resumen_mensual**.
- Confirmar el almacenamiento de los indicadores mensuales.
- Validar los resultados del proceso de agregación.
- Comprobar la persistencia de los datos transformados.

### Consulta SQL utilizada

```sql
SELECT *
FROM resumen_mensual;
```

In [36]:
pd.read_sql_query(
    "SELECT * FROM resumen_mensual",
    conn
)

,mes,total_pedidos,unidades_vendidas,ingreso_bruto_total,ingreso_neto_total
0,2024-01,8,71.0,12425.0,11446.00
1,2024-02,8,97.0,10720.0,9725.00
2,2024-03,9,98.0,13505.0,12459.00
3,2024-04,9,107.0,16260.0,14659.00
4,2024-05,9,97.0,11015.0,9724.75
5,2024-06,5,73.0,9230.0,8286.75

## Validación de la tabla cumplimiento_vendedores

Como parte de la fase final de validación, se consulta la tabla **cumplimiento_vendedores**, la cual contiene los indicadores de desempeño comercial calculados para cada vendedor.

Esta tabla integra la información de ingresos netos generados por las ventas y las metas mensuales asignadas, permitiendo evaluar el nivel de cumplimiento alcanzado por cada integrante del equipo comercial.

La verificación de esta tabla confirma que el proceso de integración, cálculo y almacenamiento de indicadores fue ejecutado correctamente.

### Objetivo

- Verificar la correcta creación de la tabla **cumplimiento_vendedores**.
- Validar los cálculos de ingresos netos por vendedor.
- Confirmar el cálculo del porcentaje de cumplimiento de metas.
- Garantizar la disponibilidad de indicadores para análisis de desempeño.

### Consulta SQL utilizada

```sql
SELECT *
FROM cumplimiento_vendedores;
```

In [37]:
pd.read_sql_query(
    "SELECT * FROM cumplimiento_vendedores",
    conn
)

       vendedor  ingreso_neto_total  meta_mensual  porcentaje_cumplimiento
0       Ana L��             18249.0           NaN                      NaN
1   Carlos Ruiz             19255.5        7500.0                 256.7400
2     Luis Mora             18025.0        8000.0                 225.3125
3  Maria Torres             10771.0           NaN                      NaN